<input type="hidden" id="gameId" value="<?php echo $this->_gameInfo['id']; ?>" />
<input type="hidden" id="playerNumber" value="<?php echo $this->_playerNumber; ?>" />
<?php
if($this->_playerNumber != 1 && !$this->_gameInfo['player' . $this->_playerNumber . 'Approves']) { ?>
<div class="approvalBox">
	<h3>Ready to play?</h3>
	<div class='box button playerApproves'>YES!</div>
	<div class='box button playerRejects'>I don't want to play with them.</div>
	<div class='clear'></div>
</div>
<?php } else { ?>
	<h3>Waiting for everyone to agree to play. </h3>
<?php } ?>
<div class="box team1">
	Team 1
	<div class='box user' data-id="<?php echo $this->_gameInfo['player1Id']; ?>">
		<?php
			$this->renderChild(
				'approvalStatus.phtml',
				array(
					'name' => $this->_players[$this->_gameInfo['player1Id']]['name'],
					'approved' => true //the first player always has approved because they created the game
				)
			);
		?>
	</div>
	<div class='box user' data-id="<?php echo $this->_gameInfo['player2Id']; ?>">
		<?php
			$this->renderChild(
				'approvalStatus.phtml',
				array(
					'name' => $this->_players[$this->_gameInfo['player2Id']]['name'],
					'approved' => $this->_gameInfo['player2Approves']
				)
			);
		?>
	</div>
</div>

<div class="box team2">
	Team 2
	<div class='box user' data-id="<?php echo $this->_gameInfo['player3Id']; ?>">
				<?php
			$this->renderChild(
				'approvalStatus.phtml',
				array(
					'name' => $this->_players[$this->_gameInfo['player3Id']]['name'],
					'approved' => $this->_gameInfo['player3Approves']
				)
			);
		?>
	</div>
	<div class='box user' data-id="<?php echo $this->_gameInfo['player4Id']; ?>">
		<?php
			$this->renderChild(
				'approvalStatus.phtml',
				array(
					'name' => $this->_players[$this->_gameInfo['player4Id']]['name'],
					'approved' => $this->_gameInfo['player4Approves']
				)
			);
		?>
	</div>
</div>