
<?php if(!$this->_players[\Utils::$userInfo['id']]['approves']) { ?>
<h3>Ready to play?</h3>
<div class=teamSelection>
	<div class='box playerApproves'>YES!</div>
	<div class='box playerRejects'>I don't want to play with them</div>
	<div class='clear'></div>
	<div class="box team1">
		Team 1
		<div class='box user'>
<!--			neubie <br/> Are you in? -->
			neubie <br/> Waiting for others.
		</div>
		<div class='box user'>elocin <br/> Waiting for response.</div>
	</div>

	<div class="box team2">
		Team 2
		<div class='box user'>joolie <br/>Ready to Play!</div>
		<div class='box user'>salmon <br/>Waiting for response.</div>
	</div>
</div>
<?php } ?>