<div class="gameHeader">
	important game related stuff
</div>
<div class="gameBoard">
	<div class="partner">
		<div class="playerName">
			<?php echo $this->_players[$this->_partnerId]['name'] ?>
		</div>
		<div class="cards">
			<?php for($i = 1; $i <= count($this->_hands[$this->_partnerId]); $i++) { ?>
				
			
			
			
			
			
			<!-- 
			FIND A CARD BACK THAT IS PNG, RESIZE TO MATCH OTHER CARDS
	
			-->
			
			
			
			
			
			
			
			
			<img src="/statics/cards/card_back.jpg" />
			<?php } ?>
		</div>
	</div>
	<div class="opponentLeft">
		<div class="playerName">
			<?php echo $this->_players[$this->_opponentLeftId]['name'] ?>
		</div>
		<div class="cards"></div>
	</div>
	<div class="opponentRight">
		<div class="playerName">
			<?php echo $this->_players[$this->_opponentRightId]['name'] ?>
		</div>
		<div class="cards"></div>
	</div>
	<div class="currentPlayer">
		<div class="playerName">
			<?php echo $this->_players[\Utils::$userInfo['id']]['name']; ?>
		</div>
		<div class="cards">
			<?php foreach($this->_hands[\Utils::$userInfo['id']] as $card) { ?>
				<img src="/statics/cards/<?php echo $card['rank'] . '_' . $card['suit'] . '.png' ?>" />
			<?php } ?>
		</div>
	</div>
</div>
<script type="text/javascript">
	var gameInfo = <?php echo $this->getJSONgameInfo(); ?>;
	initializeBoard();
</script>