<div class="gameBoard">
	<div class="player1 playerId<?php echo $this->_gameInfo['player1Id']; ?>">
		<div class="playerName">
			<?php echo $this->_players[$this->_gameInfo['player1Id']]['name']; ?>
		</div>
		<div class="cards"></div>
	</div>
	<div class="player2 playerId<?php echo $this->_gameInfo['player2Id']; ?>">
		<div class="playerName">
			<?php echo $this->_players[$this->_gameInfo['player2Id']]['name']; ?>
		</div>
		<div class="cards"></div>
	</div>
	<div class="player3 playerId<?php echo $this->_gameInfo['player3Id']; ?>">
		<div class="playerName">
			<?php echo $this->_players[$this->_gameInfo['player3Id']]['name']; ?>
		</div>
		<div class="cards"></div>
	</div>
	<div class="player4 playerId<?php echo $this->_gameInfo['player4Id']; ?>">
		<div class="playerName">
			<?php echo $this->_players[$this->_gameInfo['player4Id']]['name']; ?>
		</div>
		<div class="cards"></div>
	</div>
</div>
<script type="text/javascript">
	var gameInfo = <?php echo $this->getJSONgameInfo(); ?>;
	initializeBoard();
</script>