<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
		<link rel='stylesheet' href="/statics/styles.css" />
		<script type='text/javascript' src='/statics/jquery.min.js' ></script>
		<?php foreach ($js as $script) { ?>
			<script type='text/javascript' src='<?php echo $script; ?>' ></script>
		<?php } ?>
	</head>
