CREATE TABLE cards (
  rank ENUM(
    '2','3','4','5','6','7','8','9','10','Jack','Queen','King','Ace','Joker'
  ) NOT NULL,
  suit ENUM(
    'Hearts', 'Diamonds', 'Spades', 'Clubs', 'Big', 'Little'
  ) NOT NULL
);
INSERT INTO cards VALUES
  ('2', 'Hearts'),
  ('3', 'Hearts'),
  ('4', 'Hearts'),
  ('5', 'Hearts'),
  ('6', 'Hearts'),
  ('7', 'Hearts'),
  ('8', 'Hearts'),
  ('9', 'Hearts'),
  ('10', 'Hearts'),
  ('Jack', 'Hearts'),
  ('Queen', 'Hearts'),
  ('King', 'Hearts'),
  ('Ace', 'Hearts'),
  ('2', 'Diamonds'),
  ('3', 'Diamonds'),
  ('4', 'Diamonds'),
  ('5', 'Diamonds'),
  ('6', 'Diamonds'),
  ('7', 'Diamonds'),
  ('8', 'Diamonds'),
  ('9', 'Diamonds'),
  ('10', 'Diamonds'),
  ('Jack', 'Diamonds'),
  ('Queen', 'Diamonds'),
  ('King', 'Diamonds'),
  ('Ace', 'Diamonds'),
  ('2', 'Spades'),
  ('3', 'Spades'),
  ('4', 'Spades'),
  ('5', 'Spades'),
  ('6', 'Spades'),
  ('7', 'Spades'),
  ('8', 'Spades'),
  ('9', 'Spades'),
  ('10', 'Spades'),
  ('Jack', 'Spades'),
  ('Queen', 'Spades'),
  ('King', 'Spades'),
  ('Ace', 'Spades'),
  ('2', 'Clubs'),
  ('3', 'Clubs'),
  ('4', 'Clubs'),
  ('5', 'Clubs'),
  ('6', 'Clubs'),
  ('7', 'Clubs'),
  ('8', 'Clubs'),
  ('9', 'Clubs'),
  ('10', 'Clubs'),
  ('Jack', 'Clubs'),
  ('Queen', 'Clubs'),
  ('King', 'Clubs'),
  ('Ace', 'Clubs'),
  ('Joker', 'Little'),
  ('Joker', 'Big');
